config/routes.rb
Rails.application.routes.draw do

  root 'announcements#index'

  resources :announcements

end

app/models/announcement.rb
class Announcement
  def add(announcement, posted_by, expire)
    timestamp = Time.now.to_i
    $redis.hmset("announcement:#{timestamp}", "announcement", announcement, "posted_by", posted_by)
    $redis.expire("announcement:#{timestamp}", expire)
  end

  def fetch_all
    arr = []
    announcements = $redis.keys("announcement:*")
    announcements.each { |announcement| arr << $redis.hgetall(announcement) }
    return arr
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :init_class

  def index
    @announcements = @announcement.fetch_all
  end

  def create
    @announcement.add(params[:text], params[:posted_by], params[:expire])
    redirect_to announcements_path
  end

  private

  def init_class
    @announcement = Announcement.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/announcements/index.html.erb
<% @announcements.each do |announcement|%>
  <div class="well">
    <blockquote>
      <%= announcement['announcement'] %>
    </blockquote>
    <p>
      - <%= announcement['posted_by'] %>
    </p>
  </div>
<% end %>

app/views/announcements/new.html.erb
<div class="row">
  <div class="col-md-11 well">
  <h3>Post Announcement</h3>
  <%= form_tag announcements_path, method: :post, class: "form-horizontal" do %>
    <div class="form-group">
      <%= label_tag 'text', "Announcement Text", class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= text_field_tag 'text', "", class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag 'posted_by', "Posted By", class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= text_field_tag 'posted_by', "", class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag 'expire', "Expired on (seconds)", class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= select_tag "expire", options_for_select([ 10, 20, 30, 60], 30) %>
      </div>
    </div>
    <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= button_tag "Submit", class: "btn btn-default" %>
    </div>
  </div>
  <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Announcement Wall</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Post Announcement!", new_announcement_path%></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Announcement Wall</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>

  <!-- Begin page content -->
  <div class="container">
    <%= yield %>
  </div>


</body>
</html>